replaced rome with biome as the linter
Metatavu/metatavu-home pull request #110
Opened 2024-04-02 09:21 UTC by yuusufisse

2024-04-09 08:32 UTC, Kseniia-Koshkina approved these changes

2024-04-22 06:07 UTC, Jdallos requested changes

2024-04-22 06:07 UTC, Jdallos commented on biome.json
You need to add a .vscode folder with an extensions.json file containing:
{
  "recommendations": ["biomejs.biome"]
}


This will then actually apply the linter e.g. correct indentation automatically. You will also notice that it highlights many errors in the code. Some should be fixed others e.g. suggestions about UseEffect dependency lists should be ignored for now, in fact perhaps the config could be adjusted so we don't get dependency list related errors.
If there are any errors you are unsure about just let me know.

2024-05-06 09:30 UTC, Jdallos approved these changes

2024-05-06 10:29 UTC, merged