Feature 73 on call calendar thesis work
Metatavu/metatavu-home pull request #121
Opened 2024-05-07 10:55 UTC by petri-nykanen

This PR introduces the on-call calendar UI.

- Calendar view
- List view (old on-call calendar)
- On-call card in the home screen

2024-06-20 11:50 UTC, Jdallos requested changes

2024-06-20 11:50 UTC, Jdallos commented on src/atoms/oncall.ts
> +export const oncallAtom = atom<OnCall[]>([]);
```suggestion
export const onCallAtom = atom<OnCall[]>([]);
```

2024-06-20 11:50 UTC, Jdallos commented on src/components/contexts/oncall-handler.tsx
> +  if (onCallEntry)
For clarity change to if !onCallEntry return null

2024-06-20 11:50 UTC, Jdallos commented on src/components/contexts/oncall-handler.tsx
> +        title={`${strings.timeExpressions.week} ${
Create a named variable for this string- to improve code clarity

2024-06-20 11:50 UTC, Jdallos commented on src/components/contexts/oncall-handler.tsx
> +        error={false}
Never true? If not is this needed?

2024-06-20 11:50 UTC, Jdallos commented on src/components/screens/on-call-calendar-screen.tsx
> +      setError(`${strings.error.fetchFailedGeneral}, ${error}`);
More specific error message

2024-06-20 11:50 UTC, Jdallos commented on src/components/home/oncall-card.tsx
> +      setError(`${strings.error.fetchFailedGeneral}, ${error}`);
Specific error message

2024-06-20 11:50 UTC, Jdallos commented on src/components/home/oncall-card.tsx
> +  const getOnCallData = async (year: number) => {
Docs

2024-06-20 11:50 UTC, Jdallos commented on src/components/home/oncall-card.tsx
> +const OnCallCard = () => {
Docs

2024-06-20 11:50 UTC, Jdallos commented on src/components/home/oncall-card.tsx
> +  const getCurrentOnCallPerson = () => {
Docs

2024-09-25 11:23 UTC, McDuuck commented on src/components/screens/on-call-calendar-screen.tsx
> +  useEffect(() => {
After year changes this useEffect gives error in the UI

2024-09-25 11:26 UTC, McDuuck commented on src/components/screens/on-call-calendar-screen.tsx
> +  useEffect(() => {
GET "URL" 400 (Bad Request)

2024-10-09 10:28 UTC, closed without merging