Feature 166 on call UI completion
Metatavu/metatavu-home pull request #168
Opened 2024-10-07 10:43 UTC by AfoninOleksandr

Merged develop with on-Call-UI 
Bugs included but still runs locally

2024-10-09 11:35 UTC, McDuuck approved these changes

2024-10-09 15:41 UTC, dalju005-xamk approved these changes

2024-10-14 07:48 UTC, Jdallos approved these changes

2024-10-14 07:48 UTC, Jdallos commented on src/components/contexts/oncall-handler.tsx
> +      {strings.vacationRequest.status}:{" "}
Lets try to achieve this some other way than inserting a empty sttring here e.g. how abou thave a couple of typography components (Mui) and setting a margin between them?

2024-10-14 07:48 UTC, Jdallos commented on src/components/screens/home-screen.tsx
> +
```suggestion
```

2024-10-14 07:48 UTC, Jdallos commented on src/components/screens/on-call-calendar-screen.tsx
> +  useEffect(() => {
I'm a bit suspicious of this, no need for changes now but keep this UE in mind as you start fixing bugs.

2024-10-14 07:48 UTC, Jdallos commented on src/components/screens/on-call-calendar-screen.tsx
> +   * @param year
It's good to have a bit for info in this doc e.g. 
```suggestion
   * @param year number
```

Please update other param docs that you see are missing the type of the param

2024-10-14 07:48 UTC, Jdallos commented on src/components/screens/on-call-calendar-screen.tsx
> +          {strings.oncall.onCallPersonExists}{" "}
Manage space between words with margin rather than empty string

2024-10-24 08:22 UTC, Jdallos requested changes

2024-10-24 08:22 UTC, Jdallos commented on src/App.tsx
Envs should be updated

2024-12-11 09:01 UTC, Hanhz2707 commented on src/components/contexts/oncall-handler.tsx
> +import { OnCallCalendarEntry } from "../../types";
```suggestion
import type { OnCallCalendarEntry } from "../../types";
```

2024-12-11 09:02 UTC, Hanhz2707 commented on src/components/contexts/oncall-handler.tsx
> +
Check indentation here 
```suggestion
```

2024-12-11 09:03 UTC, Hanhz2707 commented on src/components/contexts/oncall-handler.tsx
> +
Check ur indentation here

2024-12-11 11:46 UTC, rimz178 approved these changes

2025-05-12 08:10 UTC, closed without merging