Edit to questionnaires UI
Metatavu/metatavu-home pull request #195
Opened 2024-12-13 09:12 UTC by dalju005-xamk

2024-12-13 09:18 UTC, rimz178 approved these changes

2024-12-13 19:35 UTC, Hanhz2707 approved these changes

2024-12-16 08:51 UTC, McDuuck commented on src/components/questionnaire/questionnaires-edit-mode.tsx
> +              <Button
Make this look like a button

2024-12-16 09:13 UTC, McDuuck commented on src/components/questionnaire/questionnaires-edit-mode.tsx
> +   * Function to count all correct answers in the questionnaire, used for passScore determination
I would add @return docs here

2024-12-16 09:14 UTC, McDuuck commented on src/components/questionnaire/questionnaires-edit-mode.tsx
> +   * Function to update edited questionnaire
Same here

2024-12-16 09:17 UTC, McDuuck commented on src/localization/strings.ts
> +
Remove line

2024-12-16 09:27 UTC, McDuuck approved these changes
left some comments but looking very nice.

2024-12-19 09:07 UTC, Jdallos requested changes

2024-12-19 09:07 UTC, Jdallos commented on src/components/questionnaire/questionnaires-edit-mode.tsx
> +      setError(`${strings.error.questionnaireSaveFailed}, ${error}`);
Is this error message specific to updating a questionnaire rather than just saving/ creating? It should be

2024-12-19 09:07 UTC, Jdallos commented on src/components/questionnaire/questionnaires-edit-mode.tsx
> +
```suggestion
```

2024-12-19 09:07 UTC, Jdallos commented on src/components/questionnaire/questionnaires-edit-mode.tsx
> +              <Box sx={{}}>
Remove empty sx?

2024-12-19 09:07 UTC, Jdallos commented on src/localization/en.json
> +    "clearPassedUsers": "Clear passed users from this questionnaire",
```suggestion
    "clearPassedUsers": "Remove all passed users from this questionnaire",
```

2024-12-19 09:07 UTC, Jdallos commented on src/localization/en.json
> +    "snackbarMessageSuccess": "Update questionniare successfully"
```suggestion
    "snackbarMessageSuccess": "Updated questionnaire successfully"
```

2025-01-07 08:03 UTC, Jdallos approved these changes

2025-01-07 08:16 UTC, merged