merge develop -> master
Metatavu/metatavu-home pull request #33
Opened 2023-10-05 12:39 UTC by JuusoMRusanen

Merging master with develop! Let's check this code for any strange stuff before merging.

2023-10-18 07:03 UTC, petri-nykanen commented on src/App.tsx
> +    </div>
Localization provider is missing from this version.

2023-10-18 09:18 UTC, anttileppa requested changes

2023-10-18 09:18 UTC, anttileppa commented on src/components/screens/home/balance-card.tsx
> +  const [isLoading, setIsLoading] = useState(false);
verbs should be used only in method

```suggestion
  const [loading, setLoading] = useState(false);
```

2023-10-18 09:18 UTC, anttileppa commented on src/components/screens/home/balance-card.tsx
> +    const loggedInPerson = fetchedPersons.filter((person) => person.keycloakId === userProfile?.id);
Replace with find

2023-10-18 09:18 UTC, anttileppa commented on src/components/screens/home/balance-card.tsx
> +    getPersons();
Add error handling

2023-10-18 09:18 UTC, anttileppa commented on src/utils/time-utils.ts
> +    return `${Math.trunc(minutes / 60)} h ${(minutes % 60) * (String(minutes).startsWith("-")?-1 :1)} min`
Replace with proper date formatter (https://github.com/moment/luxon/blob/master/docs/formatting.md)

2023-10-19 14:24 UTC, samisii approved these changes

2023-11-01 09:18 UTC, anttileppa approved these changes

2023-11-01 09:20 UTC, merged