Production update
Metatavu/metatavu-home pull request #99
Opened 2024-02-26 14:19 UTC by yuusufisse

production Pr develop to master

2024-02-28 12:23 UTC, anttileppa requested changes

2024-02-29 10:07 UTC, yuusufisse commented on src/types/index.ts
> +export interface PersonWithTotalTime {
yes it is

2024-02-29 11:48 UTC, yuusufisse commented on src/components/layout/sync-button.tsx
> +  const getLatestDailyEntryDate = async () => {
i have split the methods into two

2024-02-29 13:55 UTC, yuusufisse commented on src/components/screens/timebank-view-all-screen.tsx
> +  const [displayedPersonsTotalTime, setDisplayedPersonsTotalTime] = useState<PersonWithTotalTime[]>(
i dont understand this request

2024-03-08 18:15 UTC, anttileppa requested changes

2024-03-08 18:15 UTC, anttileppa commented on src/components/layout/sync-button.tsx
> +  const fetchPersonsAndEntries = async () => {
This method does two things. In reactive context, you should instead have a separate method for dailyEntries in useEffect what depends on persons

2024-03-08 18:15 UTC, anttileppa commented on src/components/layout/sync-button.tsx
> +  const getLatestDailyEntryDate = async () => {
verb suggests that this is a get method but it does not actually return anything

2024-03-08 18:15 UTC, anttileppa commented on src/components/screens/timebank-screen.tsx
> +      setPersonTotalTime(fetchedPersonTotalTime[0]);
Reformat this file, there is some inconsistencies in indents

2024-03-08 18:15 UTC, anttileppa commented on src/components/screens/timebank-view-all-screen.tsx
> +  const populatePersonTotalTimeData = async (
This does not actually populate anything, rename the method to reflect what it actually does

2024-03-22 10:24 UTC, anttileppa requested changes

2024-03-22 10:24 UTC, anttileppa commented on src/components/layout/sync-button.tsx
> +    await fetchPersons();
Why this method fetches the persons? It will create forever loop, when it changes the persons array

2024-03-22 10:24 UTC, anttileppa commented on src/components/layout/sync-button.tsx
> +        setPersons(tempPersons);
This updates the atom, it might introduce some extremely weird behaviour on other components, so the persons actually be a state not atom?

2024-03-22 10:24 UTC, anttileppa commented on src/components/layout/sync-button.tsx
> +        setDailyEntries(fetchedDailyEntries);
This also changes atom instead of state, is this by purpose?

2024-03-26 11:48 UTC, yuusufisse commented on src/components/layout/sync-button.tsx
> +    if (!persons) {
it is used to check if the persons data is falsy before making the API call to fetch persons.

2024-04-02 13:01 UTC, anttileppa approved these changes

2024-04-03 08:15 UTC, merged